apiVersion: v2
name: traefik
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: traefik
    version: v35.4.0
    repository: https://traefik.github.io/charts
    skipCRDs: true
